version: '3'

services:
  postgres-compose:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'health'
    ports:
      - "5432:5432"
    expose:
      - '5432'
    volumes:
      - ~/db/:/var/lib/postgresql
