spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/health}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: true
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
